### ISSUE TITLE
Vertical lines seen in the waterfall 

### ISSUE THREAD

**Issue by janvgils** [ast/SoapyAirspy#1]
First SatNOGS observation with your code.

Looking at this waterfall https://network.satnogs.org/observations/6694954/ something is off, those parallel lines shouldn't be there.
This is a Doppler corrected observation and that is the reason for the S shape. 

The Airspy used in the observation:

```
airspy_info 
airspy_lib_version: 1.0.11

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy NOS v1.0.0-rc10-6-g4008185 2020-05-08
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x466C64C8306B65C7
Supported sample rates:
	10.000000 MSPS
	2.500000 MSPS
Close board 1
```
Running at 2.5e6 sample rate and the Soapy driver settings used `"driver=airspy,serial=466c64c8306b65c7,biastee=true"`

**Comment by janvgils** [comment]
Here an observation with a Airpsy mini https://network.satnogs.org/observations/6695041/ there we don't see the vertical parallel lines. Here we are using the following Airspy;

```
airspy_info 
airspy_lib_version: 1.0.11

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy MINI v1.0.0-rc10-6-g4008185 2020-05-08
Part ID Number: 0x6906002B 0x00000030
Serial Number: 0x04A464C83670830B
Supported sample rates:
	6.000000 MSPS
	3.000000 MSPS
Close board 1
```
Running at 3e6 sample rate and the Soapy driver settings used: `"driver=airspy,serial=4a464c83670830b,biastee=true" `

**Comment by ast** [comment]
So the driver works with the Mini but not the R2? Did I understand correctly?

**Comment by janvgils** [comment]
They behave differently, I have created multiple observation for the next couple of hours on my SatNOGS ground stations:

`https://network.satnogs.org/observations/?station=1466/` R2 at 2.5e6 and
`https://network.satnogs.org/observations/?station=2173` Mini at 3e6

**Comment by janvgils** [comment]
Nov 3th 18:55 UTC I moved back to the PothosWare SoapyAirspy version.

My first impression is, that your code has a positive influence on the Mini but not on the R2.

If I can provide more information, please let me know.

**Comment by janvgils** [comment]
I saw there where some other changes in the code, can we already give it a new try?

**Comment by ast** [comment]
I don't think I have fixed anything related to your issue yet. But I think I have a good hypothesis what it could be.

**Comment by janvgils** [comment]
Opening new issue, testing a new release.
