### ISSUE TITLE
Implement support for lower sampling rate?

### ISSUE THREAD

**Issue by LarsThunberg** [ast/SoapyAirspy#7]
Question:
Is it possible to implement support for lower sampling rates?  When running the driver in SatNOGS it seams that the Raspberry 3 has problem handling samplings rate at 3e6, I get a lot of lost samples.

**Comment by janvgils** [comment]
No, the Airspy models only support 3e6 and 6e6 when using the mini and 2.5e6 and 10e6 with the R2.

3e6 with an Airspy mini shouldn't be a problem, can you test the following: `airspy_rx -r /dev/null -a 3000000 -t 2` I wonder if it will run at 3.000 MSPS.

As a work around if you don't get it to run on 3.000 MSPS is to add the packing option. Then command will be `airspy_rx -r /dev/null -a 3000000 -p 1 -t 2`

If that is working then add the packing option `bitpack=1` here an example:

`SATNOGS_SOAPY_RX_DEVICE="driver=airspy,<your options>,bitpack=1"`

**Comment by LarsThunberg** [comment]
Thank Jan. 
I have no problem running in 3.000 MSPS with the command above. My guess is that it is a SatNOGS issue, as I see on the SatNOGS forum that more people having the same problem. It also started after an update I made from the SatNOGS setup on the 20th June.

**Comment by janvgils** [comment]
The `ooooooooooooooooo` is an indication of sample problems.

Do you experience this with all observations?

**Comment by LarsThunberg** [comment]
No, it is mostly BPSK 1200.

**Comment by janvgils** [comment]
The flow-graph that has the biggest impact on the CPU, I don't use a Pi so I can't test it.
Open a post on the SatNOGS community forum, maybe others can help.
